### ISSUE TITLE
Spike: Create tickets for work to be done: Data-Fetching

### ISSUE THREAD

**Issue by Ross-Alexandra** [Ross-Alexandra/SENG-371-Project-2#10]
This spike is being used to track the work required to create the data-fetching portion of the system.

### Acceptance Criteria
 * A series of tickets defining the overall work required to complete the data-fetching project.

**Comment by Ross-Alexandra** [comment]
@smithaustin @joshmcintosh @eetar1 

I created some tickets for this, those tickets may need to be split later as more is learned, but for now I think that is it. Please review then move this ticket along in the project.

**Comment by joshmcintosh** [comment]
Seems like a good start. I made comments on the tickets. Awaiting approval of the rest of the team before closing.

**Comment by joshmcintosh** [comment]
Closing due to lack of response.
