### ISSUE TITLE
Job Details page

### ISSUE THREAD

**Issue by Ross-Alexandra** [Ross-Alexandra/SENG-371-Project-2#20]
Blocked by GH-23

For each job that has been created, a page should exist which gives details on it (whether its completed, its ID, the dockerfile used, and the dataset used). These pages are user and job specific.

### Acceptance Criteria
 * For each job stored in the database, a page exists which can be navigated to by the job owner.
 * This job will have the following information on the job: Completed/Running, Dockerfile, and Dataset link.

**Comment by joshmcintosh** [comment]
@Ross-Alexandra this feature was added to the jobs page. Should it be changed to reflect this ticket or should this ticket be closed?

**Comment by Ross-Alexandra** [comment]
Completed as part of the final push.
