### ISSUE TITLE
Account Creation page creates new row in Users Table

### ISSUE THREAD

**Issue by Ross-Alexandra** [Ross-Alexandra/SENG-371-Project-2#24]
Blocked by GH-23 and GH-14

When an account is created, a row should be added to the database with the username and the password. 

### Acceptance Criteria
 * When an account is created, its credentials are saved in the database.

**Comment by Ross-Alexandra** [comment]
as #44 sits, it completes the functionality required by this ticket.

**Comment by joshmcintosh** [comment]
#44 is merged, thus closing this ticket.
