### ISSUE TITLE
Jobs table is updated when a job is created

### ISSUE THREAD

**Issue by Ross-Alexandra** [Ross-Alexandra/SENG-371-Project-2#27]
Blocked by GH-17 and GH-23

When a job is created, a row in entered in the jobs table.

### Acceptance Criteria
 * When a job is created by a user, a new row is created in the table.
 * A user should be linked to each job (new value in the row.)

**Comment by joshmcintosh** [comment]
Functionality in this ticket will be completed in conjunction with GH-17.
