### ISSUE TITLE
Broken Admin CSS

### ISSUE THREAD

**Issue by eetar1** [Ross-Alexandra/SENG-371-Project-2#30]
The css for the admin pages is not being found by django 

### Acceptance Criteria
 Admin CSS displays properly

**Comment by Ross-Alexandra** [comment]
.... Is there any CSS on master?

also, what project is this for?

Ethan, we need to talk about how this all works

**Comment by Ross-Alexandra** [comment]
Cant replicate on my machine, can @smithaustin and @joshmcintosh see if their admin pages render correctly?

**Comment by joshmcintosh** [comment]
It seems to work fine on my machine. Do we have a screenshot of what it should vs should not look like @eetar1?

**Comment by Ross-Alexandra** [comment]
Should look like this 
![django should](https://user-images.githubusercontent.com/30096128/53923073-b8389c80-402b-11e9-9bce-1020179ca456.png)

**Comment by Ross-Alexandra** [comment]
CSS is broken in prod. This issue is valid. Moving to low priority and adding to the User-Interface project

**Comment by Ross-Alexandra** [comment]
Did some configuration changes while hotfixing, and I believe I resolved the issue in prod. See https://seng371p2.herokuapp.com/admin/login/?next=/admin/ for verification, and please let me know when you've closed this ticket.

**Comment by Ross-Alexandra** [comment]
@eetar1 @joshmcintosh @smithaustin

**Comment by joshmcintosh** [comment]
Verified that CSS works for admin pages.
