### ISSUE TITLE
Spike: Choose data storage method

### ISSUE THREAD

**Issue by joshmcintosh** [Ross-Alexandra/SENG-371-Project-2#31]
This spike is to research and choose a method of storing client data for our containers to interact with, whether that be some sort of Git repo or a server or something.

### Acceptance Criteria ###

- A comment that is approved by the team documenting what will be used for the project

**Comment by Ross-Alexandra** [comment]
Per GH-23, we're going to be using a PostgreSQL database to hold all that info, further, this database will be hosted by ElephantSQL.

**Comment by Ross-Alexandra** [comment]
Closing due to lack of response.
