### ISSUE TITLE
Login Functionality

### ISSUE THREAD

**Issue by Ross-Alexandra** [Ross-Alexandra/SENG-371-Project-2#33]
Blocked by GH-14

Once a database is created with a table for creating users, the login page's front end must be connected to the database to check for an existing account. If the account is in the db, then a success message should be shown. If not, a failure message.

### Acceptance Criteria
* A user can login to their pre-existing account.
* When a user is logged in, they are given confirmation of login.
* When a user enters invalid credentials, they are given a failure message.

**Comment by Ross-Alexandra** [comment]
as #44 sits, it completes the functionality required by this ticket.

**Comment by joshmcintosh** [comment]
#44 is merged, thus closing this ticket.
