### ISSUE TITLE
Navigation to user datastore

### ISSUE THREAD

**Issue by Ross-Alexandra** [Ross-Alexandra/SENG-371-Project-2#34]
In order to fetch data from the user's data-store, the system must first be able to navigate to the data-store.
This ticket represents the work required for the system to successfully load the data-store (no data pull is done yet.) 

### Acceptance Criteria
 * The system, when given the necessary to go to a data store, will navigate there.

**Comment by joshmcintosh** [comment]
Do we have an idea of the types of data-stores we need to access?

**Comment by eetar1** [comment]
This can be done by using the requests library. A function like 
```    
url =  'https://landsat-pds.s3.amazonaws.com/c1/L8/139/045/LC08_L1TP_139045_20170304_20170316_01_T1/LC08_L1TP_139045_20170304_20170316_01_T1_B10_wrk.IMD'
    resp = get(url,allow_redirects=True)
    open('google.IMD', 'wb').write(resp.content)
```

This pull data from the amazon S3 store and saves to a file so for this we just need  a link to the index file of the S3 repo. This ticket will instead reflect the scraping of an index file and retrieving the links to data

**Comment by Ross-Alexandra** [comment]
Completed as part of the final push.
