### ISSUE TITLE
Create Prototype Data Algorithm

### ISSUE THREAD

**Issue by smithaustin** [Ross-Alexandra/SENG-371-Project-2#49]
**Low Priority!**
A prototype function for the docker containers that actually does something to the input data would be a great demonstration in the project to show how it works.

Since we aren't data scientists, we should probably do something really simple. I think either flipping satellite image or taking sort of image size/average value calculation. Whatever is easiest. Will require [GH-47](https://github.com/Ross-Alexandra/SENG-371-Project-2/issues/47).

### Acceptance Criteria
 * function successfully executes
 * if data is produced, it is temporarily stored before aggregation

**Comment by Ross-Alexandra** [comment]
Completed by @eetar1. Test algorithm lives in https://github.com/eetar1/Seng371-Worker
