### ISSUE TITLE
Fix failing builds due to `SQLite 3.8.3 or later is required (found 3.8.2).`

### ISSUE THREAD

**Issue by Ross-Alexandra** [Ross-Alexandra/SENG-371-Project-2#57]
Current working theory on the failed build is something going on with django (we don't list sqlite as a dependency) however this could be something to do with versioning. Looking further into this.

Based off of https://code.djangoproject.com/ticket/30055, it appears that "Ubuntu Trusty ships with SQLite 3.8.2 and will EOL in April 2019. Debian Jessie ships with 3.8.7+"

Probably has something to do with this being April 2019..... more digging to be done...

_Originally posted by @Ross-Alexandra in https://github.com/Ross-Alexandra/SENG-371-Project-2/pull/56#issuecomment-478809677_

**Comment by joshmcintosh** [comment]
Closing.
